"""
PRO TIPS - Parts 2 and 3 (continuation)
Section 2 Part 2: Multi-account strategies
Section 3: Execution Excellence
"""
from aiogram import types
from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup
from aiogram.enums import ParseMode


async def show_pro_tips_section2_part2a(callback: types.CallbackQuery, lang: str):
    """Section 2 Part 2a: Recreational bets & Book selection"""
    
    if lang == 'fr':
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 2a)</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>5️⃣ BETS 'RÉCRÉATIFS' STRATÉGIQUES</b>\n\n"
            "Controversé mais effectif.\n\n"
            "Les maths:\n"
            "• 95% arbs = $1,000/mois profit\n"
            "• 5% recreational = -$50/mois EV\n"
            "• Net: $950/mois\n"
            "• Lifespan: 2-3x plus long\n\n"
            "Types de bets récréatifs:\n"
            "• Parlays populaires ($10-20)\n"
            "• Big game spreads (Super Bowl, Finals)\n"
            "• Props mainstream\n"
            "• Losing bets mixés naturellement\n\n"
            "⚠️ Règles:\n"
            "• Moins de 5% de l'action totale\n"
            "• Small stakes seulement ($10-25)\n"
            "• Marchés populaires seulement\n"
            "• Pas overthink\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>6️⃣ SÉLECTION DE BOOKS</b>\n\n"
            "Comprends le paysage:\n\n"
            "🔵 <b>SHARP BOOKS</b> (Jamais/rarement limitent):\n"
            "• Pinnacle, Bookmaker, BetCRIS\n"
            "→ Accueillent les winners\n"
            "→ Marges plus basses\n"
            "→ Utilise pour hedges long-terme\n\n"
            "🟢 <b>SOFT BOOKS</b> (Peuvent limiter, mais smart = années):\n"
            "• Betsson, BET99, Coolbet, bet365\n"
            "• Sports Interaction, Betway\n"
            "→ Meilleures cotes sur certaines lignes\n"
            "→ PEUVENT durer années si fait bien\n"
            "→ Focus stealth tactics\n\n"
            "🟡 <b>LIMITEURS AGRESSIFS</b> (6-12 mois max):\n"
            "• FanDuel, DraftKings (books US)\n"
            "• Some smaller books\n"
            "→ Extrais value vite\n"
            "→ Attends pas long-terme\n\n"
            "Stratégie:\n"
            "• Build core sur sharp books (illimité)\n"
            "• Rotate soft books (1-3 ans chacun)\n"
            "• Burn aggressive books (extract & move)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 2a)</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>5️⃣ STRATEGIC RECREATIONAL BETS</b>\n\n"
            "Controversial but effective.\n\n"
            "The math:\n"
            "• 95% arbs = $1,000/month profit\n"
            "• 5% recreational = -$50/month EV\n"
            "• Net: $950/month\n"
            "• Lifespan: 2-3x longer\n\n"
            "Types of recreational bets:\n"
            "• Popular parlays ($10-20)\n"
            "• Big game spreads (Super Bowl, Finals)\n"
            "• Mainstream props\n"
            "• Losing bets mixed naturally\n\n"
            "⚠️ Rules:\n"
            "• Under 5% of total action\n"
            "• Small stakes only ($10-25)\n"
            "• Popular markets only\n"
            "• Don't overthink\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>6️⃣ BOOK SELECTION</b>\n\n"
            "Understand the landscape:\n\n"
            "🔵 <b>SHARP BOOKS</b> (Never/rarely limit):\n"
            "• Pinnacle, Bookmaker, BetCRIS\n"
            "→ Welcome winners\n"
            "→ Lower margins\n"
            "→ Use for long-term hedges\n\n"
            "🟢 <b>SOFT BOOKS</b> (May limit, smart = years):\n"
            "• Betsson, BET99, Coolbet, bet365\n"
            "• Sports Interaction, Betway\n"
            "→ Better odds on some lines\n"
            "→ CAN last years if done right\n"
            "→ Focus stealth tactics\n\n"
            "🟡 <b>AGGRESSIVE LIMITERS</b> (6-12 months max):\n"
            "• FanDuel, DraftKings (US books)\n"
            "• Some smaller books\n"
            "→ Extract value fast\n"
            "→ Don't expect long-term\n\n"
            "Strategy:\n"
            "• Build core on sharp books (unlimited)\n"
            "• Rotate soft books (1-3 years each)\n"
            "• Burn aggressive books (extract & move)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="➡️ Part 2b: Multi-Accounts" if lang == 'en' else "➡️ Part 2b: Multi-Comptes",
            callback_data="guide_pro_tips_2c"
        )],
        [InlineKeyboardButton(
            text="◀️ Section 2 (Part 1)" if lang == 'en' else "◀️ Section 2 (Part 1)",
            callback_data="guide_pro_tips_2"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )


async def show_pro_tips_section2_part2b(callback: types.CallbackQuery, lang: str):
    """Section 2 Part 2b: Multi-account strategies & timelines"""
    
    if lang == 'fr':
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 2b)</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>TIER 2: TACTIQUES AVANCÉES</b>\n\n"
            "⚠️ <b>DISCLAIMER IMPORTANT:</b>\n"
            "Techniquement contre ToS de la plupart des books.\n"
            "Présenté pour éducation.\n"
            "Chacun évalue ses propres risques.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>7️⃣ UTILISER COMPTES DE CONFIANCE</b>\n\n"
            "La réalité:\n"
            "Beaucoup d'arbers à succès utilisent comptes de personnes de confiance.\n\n"
            "✅ <b>Approche PLUS SÛRE:</b>\n"
            "• Ami/famille avec NOM DIFFÉRENT\n"
            "• Personne qui bet DÉJÀ récréativement\n"
            "• ILS gardent contrôle du compte (pas toi)\n"
            "• Tu les conseilles sur bets\n"
            "• ILS placent eux-mêmes\n"
            "• Profits split selon accord\n\n"
            "Pourquoi moins risqué:\n"
            "• Compte a historique naturel\n"
            "• Pas que des arbs (ils bet autre chose)\n"
            "• KYC match personne qui bet\n"
            "• IP/device match patterns usuels\n\n"
            "Exemple setup:\n"
            "Ton ami Marc:\n"
            "• Bet déjà NFL chaque weekend\n"
            "• Tu lui montres NBA arbs\n"
            "• Il les place (son device, son IP)\n"
            "• Il continue bet NFL casual\n"
            "• Compte ressemble: 'Bettor récréatif qui a découvert NBA props'\n"
            "• Peut durer: 2-5 ans facilement\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>🎯 PRINCIPES CLÉS</b>\n\n"
            "1️⃣ <b>POLYVALENCE = TOUT</b>\n"
            "• Pas SEULEMENT arb sur ce compte\n"
            "• Mix bets récréatifs\n"
            "• Différents sports/types\n"
            "• Look comme normal bettor\n\n"
            "2️⃣ <b>PATTERNS NATURELS</b>\n"
            "• Utilise leur device/IP habituel\n"
            "• Bet pendant leurs heures normales\n"
            "• Garde leur style récréatif\n"
            "• Ajoute arbs graduellement\n\n"
            "3️⃣ <b>HISTORIQUE COMPTE COMPTE</b>\n"
            "• Nouveau compte + only arbs = 6 mois max\n"
            "• Compte établi + bets diversifiés = années\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>CONSIDÉRATIONS LÉGALES</b>\n\n"
            "📋 <b>Terms of Service:</b>\n"
            "La plupart des books prohibent:\n"
            "• Une personne utilisant plusieurs comptes\n"
            "• Parier pour quelqu'un d'autre\n"
            "• Partager accès compte\n\n"
            "Violer ToS peut résulter en:\n"
            "• Fermeture compte\n"
            "• Confiscation fonds\n"
            "• Ban permanent\n\n"
            "🏛️ <b>Statut légal:</b>\n"
            "• Au Canada: Pas illégal (civil, pas criminel)\n"
            "• Pire cas: Book garde fonds et te ban\n"
            "• Pas de charges criminelles pour ToS\n"
            "• Mais quand même breach of contract\n\n"
            "💡 <b>Notre position:</b>\n"
            "• On présente toutes les options pour éducation\n"
            "• TU décides ton niveau de risque\n"
            "• Plus sûr = stick à tes propres comptes\n"
            "• Plus risqué = comptes de confiance (comprends conséquences)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>TIMELINES RÉALISTES</b>\n\n"
            "<b>Stratégie A:</b> Tes comptes seulement, pure arbing\n"
            "• Soft books: 6-18 mois\n"
            "• Sharp books: Illimité\n"
            "• Total profit: $15k-30k avant limits\n\n"
            "<b>Stratégie B:</b> Tes comptes, smart stealth\n"
            "• Soft books: 1-3 ans\n"
            "• Sharp books: Illimité\n"
            "• Total profit: $40k-80k avant limits\n\n"
            "<b>Stratégie C:</b> Comptes multiples de confiance, polyvalent\n"
            "• Chaque compte: 2-5 ans\n"
            "• 3-4 comptes en rotation\n"
            "• Total profit: $100k-200k+ sur 3-5 ans\n\n"
            "📈 La différence:\n"
            "Stratégie A: Burn rapide, restart requis\n"
            "Stratégie B: Opération solo durable\n"
            "Stratégie C: Opération multi-compte pro (plus risqué, plus reward)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>💡 VÉRITÉS SUR LES LIMITES:</b>\n\n"
            "1️⃣ Limites ne sont PAS garanties\n"
            "2️⃣ Comportement compte PLUS que volume\n"
            "3️⃣ Books sont des businesses\n"
            "4️⃣ Diversification = clé\n"
            "5️⃣ C'est un marathon\n\n"
            "Approche pro:\n"
            "• Année 1: $30k-50k\n"
            "• Année 2-3: $60k-100k/an\n"
            "• Année 4+: $100k-200k/an\n\n"
            "Approche amateur:\n"
            "• Mois 1-2: $5k-10k (burn tout vite)\n"
            "• Mois 3: Tous limités, can't continue\n\n"
            "Choisis sagement. 🎯\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 2)</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>5️⃣ STRATEGIC RECREATIONAL BETS</b>\n\n"
            "Controversial but effective.\n\n"
            "The math:\n"
            "• 95% arbs = $1,000/month profit\n"
            "• 5% recreational = -$50/month EV\n"
            "• Net: $950/month\n"
            "• Lifespan: 2-3x longer\n\n"
            "Types of recreational bets:\n"
            "• Popular parlays ($10-20)\n"
            "• Big game spreads (Super Bowl, Finals)\n"
            "• Mainstream props\n"
            "• Losing bets mixed naturally\n\n"
            "⚠️ Rules:\n"
            "• Under 5% of total action\n"
            "• Small stakes only ($10-25)\n"
            "• Popular markets only\n"
            "• Don't overthink\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>6️⃣ BOOK SELECTION</b>\n\n"
            "Understand the landscape:\n\n"
            "🔵 <b>SHARP BOOKS</b> (Never/rarely limit):\n"
            "• Pinnacle, Bookmaker, BetCRIS\n"
            "→ Welcome winners\n"
            "→ Lower margins\n"
            "→ Use for long-term hedges\n\n"
            "🟢 <b>SOFT BOOKS</b> (May limit, but smart play = years):\n"
            "• Betsson, BET99, Coolbet, bet365\n"
            "• Sports Interaction, Betway\n"
            "→ Better odds on some lines\n"
            "→ CAN last years if done right\n"
            "→ Focus stealth tactics\n\n"
            "🟡 <b>AGGRESSIVE LIMITERS</b> (6-12 months max):\n"
            "• FanDuel, DraftKings (US books)\n"
            "• Some smaller books\n"
            "→ Extract value fast\n"
            "→ Don't expect long-term\n\n"
            "Strategy:\n"
            "• Build core on sharp books (unlimited)\n"
            "• Rotate soft books (1-3 years each)\n"
            "• Burn aggressive books (extract & move)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>TIER 2: ADVANCED TACTICS</b>\n\n"
            "⚠️ <b>IMPORTANT DISCLAIMER:</b>\n"
            "Technically against ToS of most books.\n"
            "Presented for educational purposes.\n"
            "Each person evaluates their own risks.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>7️⃣ USING TRUSTED ACCOUNTS</b>\n\n"
            "The reality:\n"
            "Many successful arbers use trusted people's accounts.\n\n"
            "✅ <b>SAFER approach:</b>\n"
            "• Friend/family with DIFFERENT last name\n"
            "• Person who ALREADY bets recreationally\n"
            "• THEY keep control of account (not you)\n"
            "• You advise them on bets\n"
            "• THEY place bets themselves\n"
            "• Profits split accordingly\n\n"
            "Why less risky:\n"
            "• Account has natural history\n"
            "• Not just arbs (they bet other stuff)\n"
            "• KYC matches person actually betting\n"
            "• IP/device matches usual patterns\n\n"
            "Example setup:\n"
            "Your friend Marc:\n"
            "• Already bets NFL every weekend\n"
            "• You show him NBA arbs\n"
            "• He places them (his device, his IP)\n"
            "• He also keeps betting NFL casually\n"
            "• Account looks like: 'Recreational bettor who got into NBA props'\n"
            "• Can last: 2-5 years easily\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>🎯 KEY PRINCIPLES</b>\n\n"
            "1️⃣ <b>POLYVALENCE IS EVERYTHING</b>\n"
            "• Don't ONLY arb on that account\n"
            "• Mix in recreational bets\n"
            "• Different sports/types\n"
            "• Look like normal bettor\n\n"
            "2️⃣ <b>NATURAL PATTERNS</b>\n"
            "• Use their usual device/IP\n"
            "• Bet during their normal hours\n"
            "• Keep their recreational style\n"
            "• Add arbs gradually\n\n"
            "3️⃣ <b>ACCOUNT HISTORY MATTERS</b>\n"
            "• New account + only arbs = 6 months max\n"
            "• Established account + diverse bets = years\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>LEGAL & ETHICAL CONSIDERATIONS</b>\n\n"
            "📋 <b>Terms of Service:</b>\n"
            "Most books prohibit:\n"
            "• One person using multiple accounts\n"
            "• Betting on someone else's behalf\n"
            "• Sharing account access\n\n"
            "Violating ToS can result in:\n"
            "• Account closure\n"
            "• Funds confiscation\n"
            "• Permanent ban\n\n"
            "🏛️ <b>Legal status:</b>\n"
            "• In Canada: Not illegal (civil matter, not criminal)\n"
            "• Worst case: Book keeps funds and bans you\n"
            "• No criminal charges for ToS violations\n"
            "• But still breach of contract\n\n"
            "💡 <b>Our position:</b>\n"
            "• We present all options for education\n"
            "• YOU decide your risk tolerance\n"
            "• Safest = stick to your own accounts only\n"
            "• Riskier = use trusted accounts (understand consequences)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>REALISTIC TIMELINES BY STRATEGY</b>\n\n"
            "<b>Strategy A:</b> Your accounts only, pure arbing\n"
            "• Soft books: 6-18 months\n"
            "• Sharp books: Unlimited\n"
            "• Total profit: $15k-30k before limits\n\n"
            "<b>Strategy B:</b> Your accounts, smart stealth\n"
            "• Soft books: 1-3 years\n"
            "• Sharp books: Unlimited\n"
            "• Total profit: $40k-80k before limits\n\n"
            "<b>Strategy C:</b> Multiple trusted accounts, polyvalent\n"
            "• Each account: 2-5 years\n"
            "• 3-4 accounts rotation\n"
            "• Total profit: $100k-200k+ over 3-5 years\n\n"
            "📈 The difference:\n"
            "Strategy A: Fast burn, restart needed\n"
            "Strategy B: Sustainable solo operation\n"
            "Strategy C: Professional multi-account operation (higher risk, higher reward)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>💡 TRUTHS ABOUT LIMITS:</b>\n\n"
            "1️⃣ Limits are NOT guaranteed\n"
            "2️⃣ Behavior matters MORE than volume\n"
            "3️⃣ Books are businesses\n"
            "4️⃣ Diversification is key\n"
            "5️⃣ This is a marathon\n\n"
            "Professional approach:\n"
            "• Year 1: $30k-50k\n"
            "• Year 2-3: $60k-100k/year\n"
            "• Year 4+: $100k-200k/year\n\n"
            "Amateur approach:\n"
            "• Month 1-2: $5k-10k (burn everything fast)\n"
            "• Month 3: All limited, can't continue\n\n"
            "Choose wisely. 🎯\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="➡️ Section 3: Execution Excellence" if lang == 'en' else "➡️ Section 3: Excellence d'Exécution",
            callback_data="guide_pro_tips_3"
        )],
        [InlineKeyboardButton(
            text="◀️ Section 2 (Part 1)" if lang == 'en' else "◀️ Section 2 (Part 1)",
            callback_data="guide_pro_tips_2"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )


async def show_pro_tips_section3(callback: types.CallbackQuery, lang: str):
    """⚡ Section 3: Execution Excellence"""
    
    if lang == 'fr':
        text = (
            "⚡ <b>PRO TIPS - SECTION 3</b>\n"
            "⚡ <b>EXCELLENCE D'EXÉCUTION</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>CHECKLIST PRE-BET (CHAQUE BET)</b>\n\n"
            "Avant cliquer 'Place Bet':\n\n"
            "☑️ 1. <b>VÉRIF LIGNE</b>\n"
            "• Bet 1: Over 5.5 ✅\n"
            "• Bet 2: Under 5.5 ✅\n"
            "• PAS: Over 5.5 vs Under 4.5 ❌\n\n"
            "☑️ 2. <b>CHECK COTES</b>\n"
            "• Cotes actuelles proches du call?\n"
            "• +103 (call) vs +95 (maintenant) → OK ✅\n"
            "• +103 (call) vs -120 (maintenant) → SKIP ❌\n\n"
            "☑️ 3. <b>VÉRIF STAKE</b>\n"
            "• Bet 1: $682 (arrondi) ✅\n"
            "• Bet 2: $623 (ajusté) ✅\n"
            "• PAS: $682.09 exact ❌\n\n"
            "☑️ 4. <b>CONFIRM SIDE</b>\n"
            "• Bet 1: OVER ✅\n"
            "• Bet 2: UNDER ✅\n"
            "• Double check: Côtés opposés? ✅\n\n"
            "☑️ 5. <b>SIMULTANÉ READY</b>\n"
            "• Both devices/tabs ready\n"
            "• Stakes entered\n"
            "• Countdown: 3... 2... 1... PLACE!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚨 <b>DÉSASTRES COMMUNS</b>\n\n"
            "<b>Désastre 1: MAUVAIS SIDE</b>\n"
            "Erreur: Bet Over deux fois au lieu Over/Under\n"
            "Perte: -$1,303 💸\n\n"
            "Prévention:\n"
            "• Système color-coded\n"
            "• Device 1 (blue tape) = Premier leg\n"
            "• Device 2 (red tape) = Deuxième leg\n"
            "• Dis à haute voix: 'Over sur blue, Under sur red'\n\n"
            "<b>Désastre 2: LIGNE CHANGÉE</b>\n"
            "Erreur: Ligne moved 5.5 à 4.5, pas remarqué\n"
            "Résultat: Middle bet (risqué) au lieu d'arb\n\n"
            "Prévention:\n"
            "• TOUJOURS re-check ligne avant placing\n"
            "• Si ligne ≠ call → STOP\n"
            "• Recalcule comme middle ou skip\n\n"
            "<b>Désastre 3: COTES MOVED SIGNIFICATIVEMENT</b>\n"
            "Prévention:\n"
            "• Check cotes actuelles sur BOTH books\n"
            "• Use calculator pour vérifier profit exists\n"
            "• Si profit <1% → skip\n\n"
            "<b>Désastre 4: TYPO STAKE</b>\n"
            "Erreur: $682 au lieu de $68\n"
            "Résultat: 10x stake, exposition massive\n\n"
            "Prévention:\n"
            "• Type stake soigneusement\n"
            "• Visual check avant placing\n"
            "• Si looks wrong, it probably is\n\n"
            "<b>Désastre 5: PLAYER DNP</b>\n"
            "Erreur: Player rested, one side voided\n"
            "Résultat: Naked bet sur autre side\n\n"
            "Prévention:\n"
            "• Check player status avant big bets\n"
            "• Évite props 1-2h avant game\n"
            "• Si incertain, skip ou reduce stake\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⏱️ <b>TIMING OPTIMAL</b>\n\n"
            "🔴 Pas bet immédiatement:\n"
            "• Ligne just posted → Attends 2-5 min\n"
            "• Réduit profil 'sharp bettor'\n"
            "• Arbs usually still there\n\n"
            "🟢 Meilleurs moments:\n"
            "• Lunch (12-1 PM) → Peak récréatif\n"
            "• Soir (7-9 PM) → Casual bettors actifs\n"
            "• Weekends → Volume plus haut\n\n"
            "🟡 Évite si possible:\n"
            "• 3:47 AM sur ligue random\n"
            "• Millisecondes après sharp move\n"
            "• Only 'wrong' lines for books\n\n"
            "Vrai talk:\n"
            "Tu n'as pas besoin d'être premier pour make money.\n"
            "Être smart > être fastest.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>TRACKING & OPTIMISATION</b>\n\n"
            "Revue hebdo (use I BET):\n\n"
            "✅ Métriques performance:\n"
            "• Total profit\n"
            "• ROI par book\n"
            "• ROI par sport\n"
            "• Taux d'erreur exécution\n"
            "• Stake moyen\n\n"
            "📈 Identifie patterns:\n"
            "• Book A: 8.2% ROI, 50 bets → FOCUS\n"
            "• Book B: 2.1% ROI, 30 bets → Déprioritize\n"
            "• NBA: 7.5% ROI → Ton edge\n"
            "• NFL: 3.2% ROI → Moins focus\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🧠 <b>MENTAL GAME</b>\n\n"
            "❌ Tilt triggers:\n"
            "• Lost arb erreur stupide\n"
            "• Got limited meilleur book\n"
            "• Missed huge opportunity\n"
            "• Several voids in a row\n\n"
            "Quand tilted:\n"
            "🛑 <b>STOP BETTING IMMÉDIATEMENT</b>\n\n"
            "Protocole recovery:\n"
            "1. Take 30-60 min break\n"
            "2. Review objectivement\n"
            "3. Learn lesson\n"
            "4. Write it down\n"
            "5. Come back fresh tomorrow\n\n"
            "✅ Winning mindset:\n"
            "• Business, pas gambling\n"
            "• Erreurs arrivent (minimize)\n"
            "• Focus process > results\n"
            "• Long-term edge > short-term wins\n"
            "• Discipline = Profit\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>RYTHME HEBDO DURABLE</b>\n\n"
            "Lun-Ven routine:\n\n"
            "Matin (15 min):\n"
            "• Check calls overnight\n"
            "• Flag best opportunities\n"
            "• Plan timing exécution\n\n"
            "Lunch (30-45 min):\n"
            "• Place 2-3 arbs\n"
            "• Use checklist\n"
            "• Track in I BET\n\n"
            "Soir (30-45 min):\n"
            "• Place 2-3 arbs\n"
            "• Check stats\n"
            "• Plan next day\n\n"
            "Total: 1.5-2 heures/jour\n\n"
            "⚠️ Évite:\n"
            "• Betting quand fatigué (erreurs)\n"
            "• Rushing entre meetings\n"
            "• 'Catching up' après missed day\n"
            "• Marathon sessions (burnout)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🏆 <b>RÉSUMÉ FINAL PRO TIPS</b>\n\n"
            "💰 <b>Bankroll:</b>\n"
            "• 3-5% per arb\n"
            "• 1-2% per middle\n"
            "• 20% reserve always\n\n"
            "🛡️ <b>Stealth:</b>\n"
            "• Round stakes\n"
            "• Diversify sports\n"
            "• Time bets naturally\n"
            "• Look recreational\n\n"
            "⚡ <b>Execution:</b>\n"
            "• Checklist every bet\n"
            "• Verify line + odds\n"
            "• Both sides correct\n"
            "• Track and optimize\n\n"
            "🎯 <b>Mindset:</b>\n"
            "• Business not gambling\n"
            "• Process over results\n"
            "• Marathon not sprint\n"
            "• Discipline = Profit\n\n"
            "🚀 <b>Scale:</b>\n"
            "• Start conservative\n"
            "• Prove consistency\n"
            "• Scale intelligently\n"
            "• Sustainable > aggressive\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Remember:\n"
            "$2,000/mois × 3 ans = $72,000 ✅\n"
            "$8,000/mois × 4 mois = $32,000 then banned ❌\n\n"
            "<b>Play the long game. 🎯</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "⚡ <b>PRO TIPS - SECTION 3</b>\n"
            "⚡ <b>EXECUTION EXCELLENCE</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>PRE-BET CHECKLIST (EVERY BET)</b>\n\n"
            "Before clicking 'Place Bet':\n\n"
            "☑️ 1. <b>LINE VERIFICATION</b>\n"
            "• Bet 1: Over 5.5 ✅\n"
            "• Bet 2: Under 5.5 ✅\n"
            "• NOT: Over 5.5 vs Under 4.5 ❌\n\n"
            "☑️ 2. <b>ODDS CHECK</b>\n"
            "• Current odds close to call?\n"
            "• +103 (call) vs +95 (now) → OK ✅\n"
            "• +103 (call) vs -120 (now) → SKIP ❌\n\n"
            "☑️ 3. <b>STAKE VERIFICATION</b>\n"
            "• Bet 1: $682 (rounded) ✅\n"
            "• Bet 2: $623 (adjusted) ✅\n"
            "• NOT: $682.09 exact ❌\n\n"
            "☑️ 4. <b>SIDE CONFIRMATION</b>\n"
            "• Bet 1: OVER ✅\n"
            "• Bet 2: UNDER ✅\n"
            "• Double check: Opposite sides? ✅\n\n"
            "☑️ 5. <b>SIMULTANEOUS READY</b>\n"
            "• Both devices/tabs ready\n"
            "• Stakes entered\n"
            "• Countdown: 3... 2... 1... PLACE!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚨 <b>COMMON DISASTERS</b>\n\n"
            "<b>Disaster 1: WRONG SIDE</b>\n"
            "Mistake: Bet Over twice instead of Over/Under\n"
            "Loss: -$1,303 💸\n\n"
            "Prevention:\n"
            "• Color-coded system\n"
            "• Device 1 (blue tape) = First leg\n"
            "• Device 2 (red tape) = Second leg\n"
            "• Say out loud: 'Over on blue, Under on red'\n\n"
            "<b>Disaster 2: LINE CHANGED</b>\n"
            "Mistake: Line moved 5.5 to 4.5, didn't notice\n"
            "Result: Middle bet (risky) instead of arb\n\n"
            "Prevention:\n"
            "• ALWAYS re-check line before placing\n"
            "• If line ≠ call → STOP\n"
            "• Recalculate as middle or skip\n\n"
            "<b>Disaster 3: ODDS MOVED SIGNIFICANTLY</b>\n"
            "Prevention:\n"
            "• Check current odds on BOTH books\n"
            "• Use calculator to verify profit exists\n"
            "• If profit under 1% → skip\n\n"
            "<b>Disaster 4: STAKE TYPO</b>\n"
            "Mistake: $682 instead of $68\n"
            "Result: 10x stake, massive exposure\n\n"
            "Prevention:\n"
            "• Type stake carefully\n"
            "• Visual check before placing\n"
            "• If looks wrong, it probably is\n\n"
            "<b>Disaster 5: PLAYER DNP</b>\n"
            "Mistake: Player rested, one side voided\n"
            "Result: Naked bet on other side\n\n"
            "Prevention:\n"
            "• Check player status before big bets\n"
            "• Avoid props 1-2h before game\n"
            "• If uncertain, skip or reduce stake\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⏱️ <b>OPTIMAL TIMING</b>\n\n"
            "🔴 Don't bet immediately:\n"
            "• Line just posted → Wait 2-5 min\n"
            "• Reduces 'sharp bettor' profile\n"
            "• Arbs usually still there\n\n"
            "🟢 Best times:\n"
            "• Lunch (12-1 PM) → Peak recreational\n"
            "• Evening (7-9 PM) → Casual bettors active\n"
            "• Weekends → Higher volume\n\n"
            "🟡 Avoid if possible:\n"
            "• 3:47 AM on random league\n"
            "• Milliseconds after sharp move\n"
            "• Only 'wrong' lines for books\n\n"
            "Real talk:\n"
            "You don't need to be first to make money.\n"
            "Being smart > being fastest.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>TRACKING & OPTIMIZATION</b>\n\n"
            "Weekly review (use I BET):\n\n"
            "✅ Performance metrics:\n"
            "• Total profit\n"
            "• ROI per book\n"
            "• ROI per sport\n"
            "• Execution error rate\n"
            "• Average stake\n\n"
            "📈 Identify patterns:\n"
            "• Book A: 8.2% ROI, 50 bets → FOCUS\n"
            "• Book B: 2.1% ROI, 30 bets → Deprioritize\n"
            "• NBA: 7.5% ROI → Your edge\n"
            "• NFL: 3.2% ROI → Less focus\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🧠 <b>MENTAL GAME</b>\n\n"
            "❌ Tilt triggers:\n"
            "• Lost arb due to stupid error\n"
            "• Got limited on best book\n"
            "• Missed huge opportunity\n"
            "• Several voids in a row\n\n"
            "When tilted:\n"
            "🛑 <b>STOP BETTING IMMEDIATELY</b>\n\n"
            "Recovery protocol:\n"
            "1. Take 30-60 min break\n"
            "2. Review objectively\n"
            "3. Learn lesson\n"
            "4. Write it down\n"
            "5. Come back fresh tomorrow\n\n"
            "✅ Winning mindset:\n"
            "• Business, not gambling\n"
            "• Errors happen (minimize)\n"
            "• Focus process > results\n"
            "• Long-term edge > short-term wins\n"
            "• Discipline = Profit\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>SUSTAINABLE WEEKLY RHYTHM</b>\n\n"
            "Mon-Fri routine:\n\n"
            "Morning (15 min):\n"
            "• Check overnight calls\n"
            "• Flag best opportunities\n"
            "• Plan execution timing\n\n"
            "Lunch (30-45 min):\n"
            "• Place 2-3 arbs\n"
            "• Use checklist\n"
            "• Track in I BET\n\n"
            "Evening (30-45 min):\n"
            "• Place 2-3 arbs\n"
            "• Check stats\n"
            "• Plan next day\n\n"
            "Total: 1.5-2 hours/day\n\n"
            "⚠️ Avoid:\n"
            "• Betting when tired (errors)\n"
            "• Rushing between meetings\n"
            "• 'Catching up' after missed day\n"
            "• Marathon sessions (burnout)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🏆 <b>FINAL PRO TIPS SUMMARY</b>\n\n"
            "💰 <b>Bankroll:</b>\n"
            "• 3-5% per arb\n"
            "• 1-2% per middle\n"
            "• 20% reserve always\n\n"
            "🛡️ <b>Stealth:</b>\n"
            "• Round stakes\n"
            "• Diversify sports\n"
            "• Time bets naturally\n"
            "• Look recreational\n\n"
            "⚡ <b>Execution:</b>\n"
            "• Checklist every bet\n"
            "• Verify line + odds\n"
            "• Both sides correct\n"
            "• Track and optimize\n\n"
            "🎯 <b>Mindset:</b>\n"
            "• Business not gambling\n"
            "• Process over results\n"
            "• Marathon not sprint\n"
            "• Discipline = Profit\n\n"
            "🚀 <b>Scale:</b>\n"
            "• Start conservative\n"
            "• Prove consistency\n"
            "• Scale intelligently\n"
            "• Sustainable > aggressive\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Remember:\n"
            "$2,000/month × 3 years = $72,000 ✅\n"
            "$8,000/month × 4 months = $32,000 then banned ❌\n\n"
            "<b>Play the long game. 🎯</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="◀️ Section 2 (Part 2)" if lang == 'en' else "◀️ Section 2 (Part 2)",
            callback_data="guide_pro_tips_2b"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )
