"""
ALPHA EXCLUSIVE Guide Sections
Complete content for Tools, Settings, Last Call with all new features
"""
from aiogram import types
from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup
from aiogram.enums import ParseMode


async def show_tools_content(callback: types.CallbackQuery, lang: str):
    """🧮 Tools - Calculator, Stats, Settings 🔒 ALPHA EXCLUSIVE"""
    
    if lang == 'fr':
        text = (
            "🧮 <b>TOOLS - Calculateur, Stats, Settings</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Cette section couvre tous les outils ALPHA:\n"
            "• 📊 My Stats (statistiques complètes)\n"
            "• 🧮 Custom Calculator\n"
            "• ⚙️ Settings avancés\n"
            "• 🔔 Last Call\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>MY STATS - Statistiques Complètes</b>\n\n"
            "Tape /mystats pour voir:\n\n"
            "<b>1️⃣ Vue d'ensemble</b>\n"
            "• Total Profit (calculé en temps réel)\n"
            "• Total Staked\n"
            "• ROI global\n"
            "• Nombre de bets\n\n"
            "<b>2️⃣ Statistiques par catégorie</b>\n"
            "📈 Arbitrage:\n"
            "  • Win rate %\n"
            "  • Profit moyen par bet\n"
            "  • ROI %\n\n"
            "🎯 Middle:\n"
            "  • Win rate %\n"
            "  • Profit moyen\n"
            "  • ROI %\n\n"
            "💎 Good EV:\n"
            "  • Win rate %\n"
            "  • Profit moyen\n"
            "  • ROI %\n\n"
            "<b>3️⃣ Timeline - Graphique de progression</b>\n"
            "• Profit cumulé jour par jour\n"
            "• Visualisation de ta croissance\n\n"
            "<b>4️⃣ Derniers bets</b>\n"
            "• 3 bets les plus récents\n"
            "• Profit/perte de chacun\n"
            "• Date exacte (avec secondes)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🧮 <b>CUSTOM CALCULATOR</b>\n\n"
            "Clique 'Custom Calculator' sur n'importe quel call pour:\n\n"
            "• Changer le CASHH (montant total)\n"
            "• Recalculer automatiquement les stakes\n"
            "• Voir le nouveau profit\n"
            "• Voir le nouveau ROI\n\n"
            "💡 <b>Cas d'usage:</b>\n"
            "→ Call suggère $750 mais tu as $1000\n"
            "→ Tu veux parier plus/moins\n"
            "→ Tu veux tester différents montants\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚙️ <b>SETTINGS AVANCÉS</b>\n\n"
            "Voir section dédiée 'Settings Guide'\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🔔 <b>LAST CALL</b>\n\n"
            "Voir section dédiée 'Last Call'\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🧮 <b>TOOLS - Calculator, Stats, Settings</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "This section covers all ALPHA tools:\n"
            "• 📊 My Stats (complete statistics)\n"
            "• 🧮 Custom Calculator\n"
            "• ⚙️ Advanced Settings\n"
            "• 🔔 Last Call\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>MY STATS - Complete Statistics</b>\n\n"
            "Type /mystats to see:\n\n"
            "<b>1️⃣ Overview</b>\n"
            "• Total Profit (real-time calculated)\n"
            "• Total Staked\n"
            "• Overall ROI\n"
            "• Number of bets\n\n"
            "<b>2️⃣ Category Statistics</b>\n"
            "📈 Arbitrage:\n"
            "  • Win rate %\n"
            "  • Average profit per bet\n"
            "  • ROI %\n\n"
            "🎯 Middle:\n"
            "  • Win rate %\n"
            "  • Average profit\n"
            "  • ROI %\n\n"
            "💎 Good EV:\n"
            "  • Win rate %\n"
            "  • Average profit\n"
            "  • ROI %\n\n"
            "<b>3️⃣ Timeline - Progress Chart</b>\n"
            "• Cumulative profit day by day\n"
            "• Visualization of your growth\n\n"
            "<b>4️⃣ Recent Bets</b>\n"
            "• 3 most recent bets\n"
            "• Profit/loss of each\n"
            "• Exact date (with seconds)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🧮 <b>CUSTOM CALCULATOR</b>\n\n"
            "Click 'Custom Calculator' on any call to:\n\n"
            "• Change CASHH (total amount)\n"
            "• Auto-recalculate stakes\n"
            "• See new profit\n"
            "• See new ROI\n\n"
            "💡 <b>Use case:</b>\n"
            "→ Call suggests $750 but you have $1000\n"
            "→ You want to bet more/less\n"
            "→ You want to test different amounts\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚙️ <b>ADVANCED SETTINGS</b>\n\n"
            "See dedicated section 'Settings Guide'\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🔔 <b>LAST CALL</b>\n\n"
            "See dedicated section 'Last Call'\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="🏢 Next: Bookmakers" if lang == 'en' else "🏢 Suivant: Bookmakers",
            callback_data="guide_view_bookmakers"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )


async def show_settings_content(callback: types.CallbackQuery, lang: str):
    """⚙️ Settings Guide - Full Control 🔒 ALPHA EXCLUSIVE"""
    
    if lang == 'fr':
        text = (
            "⚙️ <b>SETTINGS GUIDE - Contrôle Total</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Clique sur <b>Settings</b> dans le menu pour accéder à tous les paramètres:\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "1️⃣ <b>DEFAULT BANKROLL (CASHH)</b>\n\n"
            "💰 Montant par défaut pour chaque call\n\n"
            "• Tape le montant que tu veux ($500, $750, $1000...)\n"
            "• Tous les calls utiliseront ce montant\n"
            "• Tu peux le changer avec Custom Calculator\n\n"
            "💡 <b>Recommandé:</b>\n"
            "• Débutant: $500-750\n"
            "• Intermédiaire: $750-1000\n"
            "• Avancé: $1000+\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "2️⃣ <b>FILTRES DE POURCENTAGE</b>\n\n"
            "Contrôle QUEL type de calls tu reçois:\n\n"
            "<b>📈 Filtre Arbitrage</b>\n"
            "• Min: 0.5% par défaut\n"
            "• Max: 100% par défaut\n"
            "→ Change pour ne recevoir QUE les arbs 3%+ par exemple\n\n"
            "<b>🎯 Filtre Middle</b>\n"
            "• Min: 0.5% par défaut\n"
            "• Max: 100% par défaut\n"
            "→ Concentre-toi sur les meilleurs middles\n\n"
            "<b>💎 Filtre Good EV</b>\n"
            "• Min: 0.5% par défaut\n"
            "• Max: 100% par défaut\n"
            "→ Seulement les EV+ élevés (10%+)\n\n"
            "💡 <b>Stratégie recommandée:</b>\n"
            "→ Arbitrage: 2%+ (qualité > quantité)\n"
            "→ Middle: 1%+ (bon équilibre)\n"
            "→ Good EV: 8%+ (moins de spam)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "3️⃣ <b>FILTRE PAR CASINO</b> 🎰\n\n"
            "Choisis quels casinos utiliser:\n"
            "• Sélectionne TES casinos seulement\n"
            "• Évite spam de calls inutiles\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "4️⃣ <b>FILTRE PAR SPORT</b> 🏅\n\n"
            "Choisis quels sports parier:\n"
            "🏀 Basketball • ⚽ Soccer • 🎾 Tennis\n"
            "🏒 Hockey • 🏈 Football • ⚾ Baseball • 🥊 MMA\n\n"
            "💡 Focus sur 2-3 sports = expertise max!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "5️⃣ <b>STAKE ROUNDING</b>\n\n"
            "Arrondis tes stakes (+ naturel):\n"
            "• Dollar ($127 → $127.00) ← Recommandé\n"
            "• Five ($127 → $125.00)\n"
            "• Ten ($127 → $130.00)\n\n"
            "6️⃣🎲 <b>STAKE RANDOMIZER</b> 🆕\n\n"
            "Varie tes stakes pour paraître humain!\n"
            "• Choisis montants: 1$, 5$, 10$\n"
            "• Mode Aléatoire (🔥 Recommandé)\n"
            "→ $355 devient $360 ou $350 (random!)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "7️⃣ <b>BET FOCUS MODE</b>\n\n"
            "Mode minimaliste pour focus maximum:\n\n"
            "• Cache Casino/Guide/Referral du menu\n"
            "• Les met dans Settings à la place\n"
            "• Menu plus clean et rapide\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "8️⃣ <b>MATCH TODAY ONLY</b>\n\n"
            "Filtre par date du match:\n\n"
            "• ON: Seulement les matchs AUJOURD'HUI\n"
            "• OFF: Tous les matchs (n'importe quand)\n\n"
            "💡 <b>Cas d'usage:</b>\n"
            "→ Tu veux parier tout de suite\n"
            "→ Tu ne veux pas de matchs dans 3 jours\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "9️⃣ <b>NOTIFICATIONS</b>\n\n"
            "ON/OFF global:\n\n"
            "• Good Odds Alerts (ON/OFF)\n"
            "• Middle Opportunities (ON/OFF)\n"
            "• All Notifications (ON/OFF)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🔟 <b>LANGUAGE</b>\n\n"
            "Français ou English\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>RÉSUMÉ:</b>\n\n"
            "Settings te donne un contrôle TOTAL sur:\n"
            "• Quels calls tu reçois (filtres %, casinos, sports)\n"
            "• Comment ils sont formatés (rounding, randomizer)\n"
            "• Ton expérience utilisateur (focus mode, language)\n\n"
            "Prends 2-3 minutes pour tout configurer!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "⚙️ <b>SETTINGS GUIDE - Full Control</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Click on <b>Settings</b> in the menu to access all parameters:\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "1️⃣ <b>DEFAULT BANKROLL (CASHH)</b>\n\n"
            "💰 Default amount for each call\n\n"
            "• Type the amount you want ($500, $750, $1000...)\n"
            "• All calls will use this amount\n"
            "• You can change it with Custom Calculator\n\n"
            "💡 <b>Recommended:</b>\n"
            "• Beginner: $500-750\n"
            "• Intermediate: $750-1000\n"
            "• Advanced: $1000+\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "2️⃣ <b>PERCENTAGE FILTERS</b>\n\n"
            "Control WHICH calls you receive:\n\n"
            "<b>📈 Arbitrage Filter</b>\n"
            "• Min: 0.5% default\n"
            "• Max: 100% default\n"
            "→ Change to receive ONLY 3%+ arbs for example\n\n"
            "<b>🎯 Middle Filter</b>\n"
            "• Min: 0.5% default\n"
            "• Max: 100% default\n"
            "→ Focus on best middles\n\n"
            "<b>💎 Good EV Filter</b>\n"
            "• Min: 0.5% default\n"
            "• Max: 100% default\n"
            "→ Only high EV+ (10%+)\n\n"
            "💡 <b>Recommended strategy:</b>\n"
            "→ Arbitrage: 2%+ (quality > quantity)\n"
            "→ Middle: 1%+ (good balance)\n"
            "→ Good EV: 8%+ (less spam)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "3️⃣ <b>STAKE ROUNDING</b>\n\n"
            "Round your stakes to look natural:\n\n"
            "<b>Options:</b>\n"
            "• Precise ($127.43) ← Default\n"
            "• Dollar ($127.00) ← Recommended\n"
            "• Five ($125.00) ← Very natural\n"
            "• Ten ($130.00) ← Very natural\n\n"
            "<b>Modes:</b>\n"
            "• Nearest (closest)\n"
            "• Up (round up)\n"
            "• Down (round down)\n\n"
            "💡 <b>Recommended:</b>\n"
            "→ Dollar or Five + Nearest\n"
            "→ Less suspicious for bookmakers\n\n"
            "⚠️ <b>NOTE:</b> Rounding slightly changes ROI\n"
            "but makes your bets look more natural.\n\n"
            "────────────────────────────────────────\n\n"
            "3️⃣🎲 <b>STAKE RANDOMIZER</b> 🆕\n\n"
            "Randomize your stakes to look more human!\n\n"
            "<b>Amounts:</b>\n"
            "• 1$ - Small variation\n"
            "• 5$ - Medium variation\n"
            "• 10$ - Large variation\n"
            "→ Choose 1 or multiple amounts!\n\n"
            "<b>Modes:</b>\n"
            "• ⬆️ Higher: Always add (+$5, +$10)\n"
            "• ⬇️ Lower: Always subtract (-$5, -$10)\n"
            "• 🎲 Random: Sometimes +, sometimes - (🔥 Recommended!)\n\n"
            "🎯 <b>Example Random Mode (5,10):</b>\n"
            "• Call 1: $355 → $360 (+$5) | $395 → $385 (-$10)\n"
            "• Call 2: $430 → $420 (-$10) | $320 → $325 (+$5)\n"
            "• Call 3: $350 → $360 (+$10) | $400 → $395 (-$5)\n\n"
            "🛡️ Each call = different pattern!\n"
            "Impossible to detect for bookmakers! ✅\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "4️⃣ <b>BET FOCUS MODE</b>\n\n"
            "Minimalist mode for maximum focus:\n\n"
            "• Hide Casino/Guide/Referral from menu\n"
            "• Put them in Settings instead\n"
            "• Cleaner and faster menu\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "5️⃣ <b>MATCH TODAY ONLY</b>\n\n"
            "Filter by match date:\n\n"
            "• ON: Only matches TODAY\n"
            "• OFF: All matches (anytime)\n\n"
            "💡 <b>Use case:</b>\n"
            "→ You want to bet right away\n"
            "→ You don't want matches in 3 days\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "6️⃣ <b>NOTIFICATIONS</b>\n\n"
            "Global ON/OFF:\n\n"
            "• Good Odds Alerts (ON/OFF)\n"
            "• Middle Opportunities (ON/OFF)\n"
            "• All Notifications (ON/OFF)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "7️⃣ <b>LANGUAGE</b>\n\n"
            "French or English\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>SUMMARY:</b>\n\n"
            "Settings give you TOTAL control over:\n"
            "• Which calls you receive (% filters)\n"
            "• How they're formatted (rounding)\n"
            "• Your user experience (focus mode)\n\n"
            "Take 2-3 minutes to configure everything!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="🔔 Next: Last Call" if lang == 'en' else "🔔 Suivant: Last Call",
            callback_data="guide_view_last_call"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )


async def show_last_call_content(callback: types.CallbackQuery, lang: str):
    """🔔 Last Call - Never Miss Profits 🔒 ALPHA EXCLUSIVE"""
    
    if lang == 'fr':
        text = (
            "🔔 <b>LAST CALL - Ne Manque Jamais de Profits</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Clique '🕒 Last Calls' dans le menu pour accéder.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>QU'EST-CE QUE C'EST?</b>\n\n"
            "Historique complet de TOUS les calls envoyés:\n\n"
            "• Arbitrage Alerts\n"
            "• Middle Opportunities\n"
            "• Good EV Bets\n\n"
            "Triés par date (plus récent en premier)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>FONCTIONNALITÉS</b>\n\n"
            "<b>1️⃣ Filtres par Type</b>\n\n"
            "Clique en haut pour filtrer:\n"
            "• 📊 All Calls (tous)\n"
            "• 📈 Arbitrage Only\n"
            "• 🎯 Middle Only\n"
            "• 💎 Good EV Only\n\n"
            "<b>2️⃣ Filtres par Casino</b> 🎰\n\n"
            "Filtre par bookmaker:\n"
            "• Bet99\n"
            "• Sports Interaction\n"
            "• Betway\n"
            "• Coolbet\n"
            "• Etc.\n\n"
            "💡 <b>Cas d'usage:</b>\n"
            "→ Tu es limité chez Bet99\n"
            "→ Tu veux seulement voir les calls sans Bet99\n\n"
            "<b>3️⃣ Filtre par Sport</b> 🏅\n\n"
            "Choisis quel sport voir:\n\n"
            "• 🏀 Basketball (NBA, NCAA)\n"
            "• ⚽ Soccer\n"
            "• 🎾 Tennis\n"
            "• 🏒 Hockey (NHL)\n"
            "• 🏈 Football (NFL)\n"
            "• ⚾ Baseball (MLB)\n"
            "• 🥊 MMA (UFC)\n\n"
            "💡 <b>Cas d'usage:</b>\n"
            "→ Tu aimes seulement le basketball\n"
            "→ Tu veux focus sur 1-2 sports\n"
            "→ Tu connais mieux certains sports\n\n"
            "<b>4️⃣ Details de Chaque Call</b>\n\n"
            "Clique sur un call pour voir:\n"
            "• Match complet\n"
            "• League/Sport\n"
            "• Date et heure du match\n"
            "• Stakes suggérés\n"
            "• Profit garanti\n"
            "• ROI %\n\n"
            "<b>5️⃣ Actions Disponibles</b>\n\n"
            "Sur chaque call tu peux:\n\n"
            "🧮 <b>Custom Calculator</b>\n"
            "→ Change le CASHH\n"
            "→ Recalcule tout\n\n"
            "💰 <b>I BET (tracker)</b>\n"
            "→ Sauvegarde le bet\n"
            "→ Track ton profit\n\n"
            "🔗 <b>Liens Casinos</b>\n"
            "→ Clique pour aller direct au bet\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>POURQUOI C'EST CRUCIAL</b>\n\n"
            "<b>Scénario 1: Tu as manqué une alerte</b>\n"
            "→ Tu dormais\n"
            "→ Tu étais occupé\n"
            "→ Retourne dans Last Call\n"
            "→ Le call est peut-être encore bon!\n\n"
            "<b>Scénario 2: Tu veux revoir un call</b>\n"
            "→ Tu as cliqué trop vite\n"
            "→ Tu veux vérifier les cotes\n"
            "→ Last Call = historique complet\n\n"
            "<b>Scénario 3: Tu veux analyser</b>\n"
            "→ Quel type de call est le plus fréquent?\n"
            "→ Quels casinos reviennent souvent?\n"
            "→ Quel sport a le plus d'arbs?\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>IMPORTANT</b>\n\n"
            "Les calls dans Last Call sont:\n\n"
            "✅ Toujours disponibles (historique)\n"
            "⚠️ Peut-être expirés (cotes changées)\n"
            "⚠️ Peut-être plus profitables (vérifie!)\n\n"
            "💡 <b>Conseil:</b>\n"
            "→ Utilise Last Call dans les 30-60 minutes\n"
            "→ Après, les cotes ont probablement bougé\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚀 <b>WORKFLOW OPTIMAL</b>\n\n"
            "1. Reçois call en temps réel\n"
            "2. Si occupé → ignore\n"
            "3. Plus tard → va dans Last Call\n"
            "4. Filtre par type ou casino\n"
            "5. Clique sur un call récent\n"
            "6. Vérifie les cotes sur les sites\n"
            "7. Si encore bon → BET!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🔔 <b>LAST CALL - Never Miss Profits</b> 🔒\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "Click '🕒 Last Calls' in menu to access.\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>WHAT IS IT?</b>\n\n"
            "Complete history of ALL calls sent:\n\n"
            "• Arbitrage Alerts\n"
            "• Middle Opportunities\n"
            "• Good EV Bets\n\n"
            "Sorted by date (most recent first)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>FEATURES</b>\n\n"
            "<b>1️⃣ Filters by Type</b>\n\n"
            "Click at top to filter:\n"
            "• 📊 All Calls\n"
            "• 📈 Arbitrage Only\n"
            "• 🎯 Middle Only\n"
            "• 💎 Good EV Only\n\n"
            "<b>2️⃣ Filters by Casino</b>\n\n"
            "Filter by bookmaker:\n"
            "• Bet99\n"
            "• Sports Interaction\n"
            "• Betway\n"
            "• Coolbet\n"
            "• Etc.\n\n"
            "💡 <b>Use case:</b>\n"
            "→ You're limited at Bet99\n"
            "→ You only want calls without Bet99\n\n"
            "<b>3️⃣ Details of Each Call</b>\n\n"
            "Click on a call to see:\n"
            "• Full match\n"
            "• League/Sport\n"
            "• Match date and time\n"
            "• Suggested stakes\n"
            "• Guaranteed profit\n"
            "• ROI %\n\n"
            "<b>4️⃣ Available Actions</b>\n\n"
            "On each call you can:\n\n"
            "🧮 <b>Custom Calculator</b>\n"
            "→ Change CASHH\n"
            "→ Recalculate everything\n\n"
            "💰 <b>I BET (tracker)</b>\n"
            "→ Save the bet\n"
            "→ Track your profit\n\n"
            "🔗 <b>Casino Links</b>\n"
            "→ Click to go directly to bet\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💡 <b>WHY IT'S CRUCIAL</b>\n\n"
            "<b>Scenario 1: You missed an alert</b>\n"
            "→ You were sleeping\n"
            "→ You were busy\n"
            "→ Go back to Last Call\n"
            "→ The call might still be good!\n\n"
            "<b>Scenario 2: You want to review a call</b>\n"
            "→ You clicked too fast\n"
            "→ You want to check odds\n"
            "→ Last Call = complete history\n\n"
            "<b>Scenario 3: You want to analyze</b>\n"
            "→ Which call type is most frequent?\n"
            "→ Which casinos appear often?\n"
            "→ Which sport has most arbs?\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>IMPORTANT</b>\n\n"
            "Calls in Last Call are:\n\n"
            "✅ Always available (history)\n"
            "⚠️ Possibly expired (odds changed)\n"
            "⚠️ Possibly more profitable (check!)\n\n"
            "💡 <b>Tip:</b>\n"
            "→ Use Last Call within 30-60 minutes\n"
            "→ After that, odds have probably moved\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚀 <b>OPTIMAL WORKFLOW</b>\n\n"
            "1. Receive call in real-time\n"
            "2. If busy → ignore\n"
            "3. Later → go to Last Call\n"
            "4. Filter by type or casino\n"
            "5. Click on recent call\n"
            "6. Check odds on sites\n"
            "7. If still good → BET!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [[InlineKeyboardButton(
        text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
        callback_data="learn_guide_pro"
    )]]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )
