"""
New Introduction - What is RISKO?
Explains all 3 bet types: Arbitrage, Good Odds, Middle Bets
"""
from aiogram import types
from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup
from aiogram.enums import ParseMode


async def show_introduction_new(callback: types.CallbackQuery, lang: str):
    """📖 Introduction - What is RISKO?"""
    
    if lang == 'fr':
        text = (
            "📖 <b>INTRODUCTION - QU'EST-CE QUE RISKO?</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>RISKO = PLATEFORME DE PROFIT SPORTIF</b>\n\n"
            "On t'envoie 3 types de bets profitables:\n\n"
            "1️⃣ ⚖️ ARBITRAGE (0% risque)\n"
            "→ Bet tous les résultats pour profit garanti\n"
            "→ 80% de nos calls\n"
            "→ Focus principal de ce guide\n\n"
            "2️⃣ 💎 GOOD ODDS (bets +EV)\n"
            "→ Bets simples avec valeur attendue positive\n"
            "→ Profit % plus haut, risque modéré\n"
            "→ 15% de nos calls\n\n"
            "3️⃣ 🎯 MIDDLE BETS (loterie EV+)\n"
            "→ Deux bets qui se chevauchent pour gros gains rares\n"
            "→ Potentiel de profit élevé, variance élevée\n"
            "→ 5% de nos calls\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>ARBITRAGE: LE CŒUR</b> (Notre service principal)\n\n"
            "C'est quoi?\n"
            "Parier sur TOUS les résultats possibles pour profit garanti.\n\n"
            "Comment ça marche:\n"
            "• Bookmaker A a bonnes cotes sur Team X\n"
            "• Bookmaker B a bonnes cotes sur Team Y\n"
            "• Tu bet les DEUX côtés\n"
            "• Peu importe qui gagne → TOI TU PROFIT\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>EXEMPLE ARBITRAGE</b> (Format réel du bot)\n\n"
            "🏟️ Real Madrid vs Barcelona\n"
            "⚽ La Liga - Moneyline\n"
            "💰 CASHH: $500.00\n"
            "✅ Profit Garanti: $35.08 (7.0%)\n\n"
            "🔶 [Betsson] Real Madrid gagne\n"
            "💵 Stake: $254.80 (2.10) → Return: $535.08\n\n"
            "📗 [bet365] Barcelona gagne\n"
            "💵 Stake: $245.20 (2.15) → Return: $535.08\n\n"
            "LES DEUX scénarios:\n"
            "• Real gagne: Return $535.08 → +$35.08 ✅\n"
            "• Barca gagne: Return $535.08 → +$35.08 ✅\n\n"
            "💎 Profit garanti peu importe!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>POURQUOI ARBITRAGE EST LE BEST</b>\n\n"
            "✅ Zéro risque mathématique\n"
            "✅ Pas besoin connaissance sports\n"
            "✅ Profits quotidiens constants\n"
            "✅ Scalable (plus bankroll = plus profit)\n"
            "✅ Fonctionne 24/7 (sports jamais stop)\n\n"
            "vs autres méthodes:\n"
            "❌ Betting régulier: 50% win rate, variance\n"
            "❌ Betting 'sharp': Besoin connaissance profonde\n"
            "❌ Suivre tipsters: Souvent perd long-terme\n\n"
            "Arbitrage:\n"
            "✅ Math garantit profit\n"
            "✅ Bot trouve opportunités\n"
            "✅ Tu exécutes seulement\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💰 <b>PROFITS RÉALISTES</b> (Focus arbitrage)\n\n"
            "Avec $1,000 CASHH:\n"
            "• Gratuit (2 arbs/jour): $20-40/jour → $600-1,200/mois\n"
            "• Alpha (10 arbs/jour): $100-200/jour → $3k-6k/mois\n\n"
            "Avec $5,000 CASHH:\n"
            "• Gratuit (2 arbs/jour): $100-200/jour → $3k-6k/mois\n"
            "• Alpha (20 arbs/jour): $500-1k/jour → $15k-30k/mois\n\n"
            "ROI arbitrage moyen: 3-6% par bet\n"
            "Temps moyen par bet: 2-3 minutes\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚀 <b>PROCHAINES ÉTAPES</b>\n\n"
            "Ce guide focus principalement sur ARBITRAGE:\n"
            "• Comment ça marche (cette section) ✅\n"
            "• Modes SAFE vs RISKED (prochaine)\n"
            "• Comment exécuter proprement\n"
            "• Éviter erreurs\n"
            "• Rester sous radar\n"
            "• Maximiser profits\n\n"
            "Pour Good Odds & Middle Bets:\n"
            "→ Voir sections dédiées (Alpha seulement)\n\n"
            "Plongeons dans les modes d'arbitrage! 👇\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "📖 <b>INTRODUCTION - WHAT IS RISKO?</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>RISKO = SPORTS BETTING PROFIT PLATFORM</b>\n\n"
            "We send you 3 types of profitable bets:\n\n"
            "1️⃣ ⚖️ ARBITRAGE (0% risk)\n"
            "→ Bet on all outcomes for guaranteed profit\n"
            "→ 80% of our calls\n"
            "→ Main focus of this guide\n\n"
            "2️⃣ 💎 GOOD ODDS (+EV bets)\n"
            "→ Single bets with positive expected value\n"
            "→ Higher profit %, moderate risk\n"
            "→ 15% of our calls\n\n"
            "3️⃣ 🎯 MIDDLE BETS (EV+ lottery)\n"
            "→ Two overlapping bets for rare big wins\n"
            "→ High profit potential, high variance\n"
            "→ 5% of our calls\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>ARBITRAGE: THE CORE</b> (Our main service)\n\n"
            "What is it?\n"
            "Betting on ALL possible outcomes for guaranteed profit.\n\n"
            "How it works:\n"
            "• Bookmaker A has good odds on Team X\n"
            "• Bookmaker B has good odds on Team Y\n"
            "• You bet BOTH sides\n"
            "• No matter who wins → YOU PROFIT\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>ARBITRAGE EXAMPLE</b> (Real format from bot)\n\n"
            "🏟️ Real Madrid vs Barcelona\n"
            "⚽ La Liga - Moneyline\n"
            "💰 CASHH: $500.00\n"
            "✅ Guaranteed Profit: $35.08 (7.0%)\n\n"
            "🔶 [Betsson] Real Madrid to win\n"
            "💵 Stake: $254.80 (2.10) → Return: $535.08\n\n"
            "📗 [bet365] Barcelona to win\n"
            "💵 Stake: $245.20 (2.15) → Return: $535.08\n\n"
            "BOTH scenarios:\n"
            "• Real wins: Return $535.08 → +$35.08 ✅\n"
            "• Barca wins: Return $535.08 → +$35.08 ✅\n\n"
            "💎 Guaranteed profit no matter what!\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚖️ <b>WHY ARBITRAGE IS THE BEST</b>\n\n"
            "✅ Zero mathematical risk\n"
            "✅ No sports knowledge needed\n"
            "✅ Consistent daily profits\n"
            "✅ Scalable (more bankroll = more profit)\n"
            "✅ Works 24/7 (sports never stop)\n\n"
            "vs other betting methods:\n"
            "❌ Regular betting: 50% win rate, variance\n"
            "❌ 'Sharp' betting: Need deep sports knowledge\n"
            "❌ Following tipsters: Often lose long-term\n\n"
            "Arbitrage:\n"
            "✅ Math guarantees profit\n"
            "✅ Bot finds opportunities for you\n"
            "✅ You just execute\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "💰 <b>REALISTIC PROFITS</b> (Arbitrage focus)\n\n"
            "With $1,000 CASHH:\n"
            "• Free (2 arbs/day): $20-40/day → $600-1,200/month\n"
            "• Alpha (10 arbs/day): $100-200/day → $3k-6k/month\n\n"
            "With $5,000 CASHH:\n"
            "• Free (2 arbs/day): $100-200/day → $3k-6k/month\n"
            "• Alpha (20 arbs/day): $500-1k/day → $15k-30k/month\n\n"
            "Average arbitrage ROI: 3-6% per bet\n"
            "Average time per bet: 2-3 minutes\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🚀 <b>NEXT STEPS</b>\n\n"
            "This guide focuses primarily on ARBITRAGE:\n"
            "• How it works (this section) ✅\n"
            "• SAFE vs RISKED modes (next)\n"
            "• How to execute properly\n"
            "• Avoiding mistakes\n"
            "• Staying under radar\n"
            "• Maximizing profits\n\n"
            "For Good Odds & Middle Bets:\n"
            "→ See dedicated sections (Alpha only)\n\n"
            "Let's dive into the different arbitrage modes! 👇\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="➡️ Next: SAFE vs RISKED" if lang == 'en' else "➡️ Suivant: SAFE vs RISKED",
            callback_data="guide_view_modes"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )
