"""
PRO TIPS - Complete Version (3 Massive Sections)
Professional-grade tips for $200/month service
"""
from aiogram import types
from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup
from aiogram.enums import ParseMode


async def show_pro_tips_section1(callback: types.CallbackQuery, lang: str):
    """🌟 PRO TIPS - Section 1: Bankroll Management"""
    
    if lang == 'fr':
        text = (
            "🌟 <b>PRO TIPS - SECTION 1</b>\n"
            "💰 <b>GESTION DE BANKROLL PAR TYPE DE BET</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>TABLEAU DE SIZING</b>\n\n"
            "<code>"
            "Type          Risk    Stake/Bet   Min Bank\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "⚖️ Arbitrage    0%     3-5%       20-30x\n"
            "🎯 Safe Middle  Low    1-2%       50-100x\n"
            "🔥 Lotto Middle High   0.5-1%     100-200x\n"
            "💎 Good Odds    Med    1-2%       50-100x\n"
            "</code>\n\n"
            "<b>Exemple avec $2,000 bankroll:</b>\n"
            "• Arbitrage: $60-100/bet (80% de l'action)\n"
            "• Safe Middles: $20-40/bet (15% de l'action)\n"
            "• Lotto Middles: $10-20/bet (5% de l'action)\n\n"
            "🎯 <b>LA RÈGLE 80/15/5:</b>\n"
            "• 80% → Safe arbitrage (pain quotidien)\n"
            "• 15% → Middles calculés (épice)\n"
            "• 5% → Lotto haute variance (moonshots)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>RISQUES OPÉRATIONNELS</b>\n\n"
            "Pourquoi 3-5% max par arb malgré 'zéro risque'?\n\n"
            "<b>Risques réels:</b>\n"
            "❌ Cotes bougent pendant l'exécution\n"
            "❌ Un côté annulé (DNP, mauvaise ligne)\n"
            "❌ Erreur de saisie ($682 au lieu de $682.09)\n"
            "❌ Compte limité mid-bet\n"
            "❌ Différences de règles (OT, annulation)\n\n"
            "<b>Protection:</b>\n"
            "✅ Jamais >5% par arb\n"
            "✅ Garde 20%+ bankroll en réserve\n"
            "✅ Spreadsheet des bets 'half placed'\n\n"
            "<b>Exemple catastrophe:</b>\n"
            "• Tu places Over 5.5 @ BetMGM ($682)\n"
            "• Avant Under, tu es limité ❌\n"
            "• Maintenant tu as un bet nu (pas hedgé)\n"
            "• Si tu avais 10 arbs ce jour → désastre\n\n"
            "Avec 3-5% par bet:\n"
            "• Un bet nu = gérable\n"
            "• Tu peux hedger ailleurs ou accepter le risque\n"
            "• Ta bankroll survit\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎲 <b>MIDDLE BETS: LES MATHS</b>\n\n"
            "Exemple (ton call typique):\n"
            "💰 Stake: $200 total\n"
            "🎯 Si middle hit (15%): +$182\n"
            "📊 Si middle miss (85%): -$9\n\n"
            "<b>Calcul EV:</b>\n"
            "(0.15 × $182) + (0.85 × -$9)\n"
            "= $27.30 - $7.65 = <b>+$19.65</b>\n\n"
            "ROI: $19.65 / $200 = <b>9.8% ✅</b>\n\n"
            "🚨 <b>CRITIQUE:</b> Seulement +EV si p_middle ≥ 4.7%\n\n"
            "Si vraie probabilité = 3%:\n"
            "(0.03 × $182) + (0.97 × -$9)\n"
            "= $5.46 - $8.73 = <b>-$3.27 ❌</b>\n\n"
            "<b>Leçon:</b>\n"
            "• Middles = estimates précis requis\n"
            "• Variance ÉNORME (15-20 pertes pour 1 win)\n"
            "• Stakes petits (0.5-2% bankroll)\n"
            "• Track sur 50+ bets minimum\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📈 <b>STRATÉGIE DE CROISSANCE</b>\n\n"
            "<b>Mois 1-3: BUILD THE BASE</b>\n"
            "• Start: $1,000-2,000\n"
            "• Focus: 100% arbitrage\n"
            "• Goal: Prouver la consistance\n"
            "• Retrait: 0% (réinvestir tout)\n\n"
            "<b>Mois 4-6: SCALE UP</b>\n"
            "• Bankroll: $3,000-5,000\n"
            "• Mix: 85% arb / 15% middles\n"
            "• Goal: Augmenter le volume\n"
            "• Retrait: 20-30% des profits\n\n"
            "<b>Mois 6-12: OPTIMIZE</b>\n"
            "• Bankroll: $6,000-10,000+\n"
            "• Mix: 75% arb / 20% middles / 5% lotto\n"
            "• Goal: Maximiser l'edge\n"
            "• Retrait: 50% des profits\n\n"
            "<b>Reality check:</b>\n"
            "• Certains books vont te limiter (6-12 mois)\n"
            "• C'est NORMAL pour certains books\n"
            "• Mais joueurs smart = ANNÉES sur d'autres\n"
            "• La stratégie compte (voir Section 2)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🌟 <b>PRO TIPS - SECTION 1</b>\n"
            "💰 <b>BANKROLL MANAGEMENT BY BET TYPE</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📊 <b>SIZING TABLE</b>\n\n"
            "<code>"
            "Type          Risk    Stake/Bet   Min Bank\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            "⚖️ Arbitrage    0%     3-5%       20-30x\n"
            "🎯 Safe Middle  Low    1-2%       50-100x\n"
            "🔥 Lotto Middle High   0.5-1%     100-200x\n"
            "💎 Good Odds    Med    1-2%       50-100x\n"
            "</code>\n\n"
            "<b>Example with $2,000 bankroll:</b>\n"
            "• Arbitrage: $60-100/bet (80% of action)\n"
            "• Safe Middles: $20-40/bet (15% of action)\n"
            "• Lotto Middles: $10-20/bet (5% of action)\n\n"
            "🎯 <b>THE 80/15/5 RULE:</b>\n"
            "• 80% → Safe arbitrage (bread & butter)\n"
            "• 15% → Calculated middles (spice)\n"
            "• 5% → High-variance lotto (moonshots)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>OPERATIONAL RISKS</b>\n\n"
            "Why 3-5% max per arb despite 'zero risk'?\n\n"
            "<b>Real risks:</b>\n"
            "❌ Odds move during execution\n"
            "❌ One side gets voided (DNP, wrong line)\n"
            "❌ Entry error ($682 instead of $682.09)\n"
            "❌ Account limited mid-bet\n"
            "❌ Rule differences (OT, cancellation)\n\n"
            "<b>Protection:</b>\n"
            "✅ Never stake >5% per arb\n"
            "✅ Keep 20%+ bankroll in reserve\n"
            "✅ Spreadsheet of 'half placed' bets\n\n"
            "<b>Example disaster:</b>\n"
            "• You place Over 5.5 @ BetMGM ($682)\n"
            "• Before placing Under, you're limited ❌\n"
            "• Now you have a naked bet (not hedged)\n"
            "• If you had 10 more arbs that day → disaster\n\n"
            "With 3-5% per bet:\n"
            "• One naked bet = manageable\n"
            "• You can hedge elsewhere or accept risk\n"
            "• Your bankroll survives\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎲 <b>MIDDLE BETS: THE MATH</b>\n\n"
            "Example (your typical call):\n"
            "💰 Stake: $200 total\n"
            "🎯 If middle hits (15%): +$182\n"
            "📊 If middle misses (85%): -$9\n\n"
            "<b>EV calculation:</b>\n"
            "(0.15 × $182) + (0.85 × -$9)\n"
            "= $27.30 - $7.65 = <b>+$19.65</b>\n\n"
            "ROI: $19.65 / $200 = <b>9.8% ✅</b>\n\n"
            "🚨 <b>CRITICAL:</b> Only +EV if p_middle ≥ 4.7%\n\n"
            "If real probability is only 3%:\n"
            "(0.03 × $182) + (0.97 × -$9)\n"
            "= $5.46 - $8.73 = <b>-$3.27 ❌</b>\n\n"
            "<b>Lesson:</b>\n"
            "• Middles require accurate probability estimates\n"
            "• Variance is HUGE (15-20 losses for 1 win)\n"
            "• Keep stakes small (0.5-2% of bankroll)\n"
            "• Track results over 50+ bets minimum\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "📈 <b>BANKROLL GROWTH STRATEGY</b>\n\n"
            "<b>Month 1-3: BUILD THE BASE</b>\n"
            "• Start: $1,000-2,000\n"
            "• Focus: 100% arbitrage\n"
            "• Goal: Prove consistency\n"
            "• Withdraw: 0% (reinvest everything)\n\n"
            "<b>Month 4-6: SCALE UP</b>\n"
            "• Bankroll: $3,000-5,000\n"
            "• Mix: 85% arb / 15% middles\n"
            "• Goal: Increase volume\n"
            "• Withdraw: 20-30% of profits\n\n"
            "<b>Month 6-12: OPTIMIZE</b>\n"
            "• Bankroll: $6,000-10,000+\n"
            "• Mix: 75% arb / 20% middles / 5% lotto\n"
            "• Goal: Maximize edge\n"
            "• Withdraw: 50% of profits\n\n"
            "<b>Reality check:</b>\n"
            "• Some books will limit you (6-12 months)\n"
            "• This is NORMAL for certain books\n"
            "• But smart players last YEARS on others\n"
            "• Strategy matters (see Section 2)\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="➡️ Section 2: Staying Under Radar" if lang == 'en' else "➡️ Section 2: Rester Sous le Radar",
            callback_data="guide_pro_tips_2"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )


# Section 2 sera trop longue, on la divise en 2 parties
async def show_pro_tips_section2_part1(callback: types.CallbackQuery, lang: str):
    """🛡️ PRO TIPS - Section 2 Part 1: Stealth Tactics"""
    
    if lang == 'fr':
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 1)</b>\n"
            "🛡️ <b>RESTER SOUS LE RADAR</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>REALITY CHECK:</b>\n\n"
            "Certains books limitent les winners agressivement.\n"
            "D'autres sont plus tolérants si tu es smart.\n\n"
            "<b>TON OBJECTIF:</b> Maximiser lifespan sur soft books\n"
            "<b>RÉALITÉ:</b> Joueurs smart = 1-5+ ANNÉES, pas mois\n\n"
            "Comment? Lis ci-dessous. 👇\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>TIER 1: TACTIQUES STEALTH LÉGITIMES</b>\n\n"
            "100% légal et dans les ToS:\n\n"
            "<b>1️⃣ ARRONDIS TES STAKES</b>\n\n"
            "❌ Mauvais: $682.09, $847.37, $1,234.56\n"
            "✅ Bon: $680, $850, $1,235\n\n"
            "Pourquoi ça compte:\n"
            "• Cents exacts = crie 'calculator bot'\n"
            "• Arrondi = normal bettor\n\n"
            "Implémentation:\n"
            "• Arrondi au $5-10 le plus proche\n"
            "• Ajuste 2e leg pour compenser\n"
            "• Petite différence profit (moins de 1%) vaut le coup\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>2️⃣ DIVERSIFIE SPORTS & MARCHÉS</b>\n\n"
            "❌ Profil red flag:\n"
            "• 100% NBA player props\n"
            "• Seulement marchés obscurs\n"
            "• Jamais bet games populaires\n\n"
            "✅ Profil smart:\n"
            "• 70% ton meilleur sport (NBA)\n"
            "• 30% autres sports (NHL, NFL, MLB)\n"
            "• Mix de props, spreads, totals, ML\n\n"
            "Exemple semaine:\n"
            "Lun: NBA arb + NFL recreational bet\n"
            "Mar: NHL arb\n"
            "Mer: NBA arb + Soccer arb\n"
            "Jeu: MLB arb\n"
            "Ven: NBA arb + NHL recreational\n\n"
            "Pattern: Looks diverse, not robotic\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>3️⃣ STRATÉGIE DE TIMING</b>\n\n"
            "❌ Red flags:\n"
            "• Bet secondes après ligne postée\n"
            "• Seulement bet closing lines\n"
            "• 3:47 AM sur ligue turque\n"
            "• Exécution parfaite chaque fois\n\n"
            "✅ Smart timing:\n"
            "• Attends 2-5 min après post\n"
            "• Bet pendant peak hours (12-1 PM, 7-9 PM)\n"
            "• Occasionnel bets retardés\n"
            "• Some weekends, some weekdays\n\n"
            "Réalité: Good arbs durent 10-30 minutes\n"
            "Pas besoin d'être PREMIER, juste assez rapide\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>4️⃣ PATTERNS DE RETRAIT</b>\n\n"
            "❌ Pattern évident:\n"
            "• Deposit lundi\n"
            "• Arb toute la semaine\n"
            "• Retrait vendredi\n"
            "• Répéter forever\n\n"
            "✅ Pattern naturel:\n"
            "• Deposit montants raisonnables\n"
            "• Laisse balance fluctuer\n"
            "• Retrait mensuel ou bi-mensuel\n"
            "• Garde 20-30% balance sur book\n\n"
            "Exemple:\n"
            "Semaine 1: Deposit $1,500\n"
            "Semaine 2-4: Bet, balance → $2,300\n"
            "Semaine 5: Retrait $800\n"
            "Continue avec $1,500 balance\n\n"
            "Ressemble à: Winner récréatif\n"
            "Pas: Arbitrageur professionnel\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    else:
        text = (
            "🛡️ <b>PRO TIPS - SECTION 2 (Part 1)</b>\n"
            "🛡️ <b>STAYING UNDER THE RADAR</b>\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "⚠️ <b>REALITY CHECK:</b>\n\n"
            "Some books limit winning players aggressively.\n"
            "Others are more tolerant if you're smart.\n\n"
            "<b>YOUR GOAL:</b> Maximize lifespan on soft books\n"
            "<b>REALITY:</b> Smart players last 1-5+ YEARS, not months\n\n"
            "How? Read below. 👇\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "🎯 <b>TIER 1: LEGITIMATE STEALTH TACTICS</b>\n\n"
            "100% legal and within ToS:\n\n"
            "<b>1️⃣ ROUND YOUR STAKES</b>\n\n"
            "❌ Bad: $682.09, $847.37, $1,234.56\n"
            "✅ Good: $680, $850, $1,235\n\n"
            "Why it matters:\n"
            "• Exact cents = screams 'calculator bot'\n"
            "• Rounded = looks like normal bettor\n\n"
            "Implementation:\n"
            "• Round to nearest $5-10\n"
            "• Adjust second leg to compensate\n"
            "• Small profit difference (under 1%) is worth it\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>2️⃣ DIVERSIFY SPORTS & MARKETS</b>\n\n"
            "❌ Red flag profile:\n"
            "• 100% NBA player props\n"
            "• Only obscure markets\n"
            "• Never bet popular games\n\n"
            "✅ Smart profile:\n"
            "• 70% your best sport (NBA)\n"
            "• 30% other sports (NHL, NFL, MLB)\n"
            "• Mix of props, spreads, totals, ML\n\n"
            "Example week:\n"
            "Mon: NBA arb + NFL recreational bet\n"
            "Tue: NHL arb\n"
            "Wed: NBA arb + Soccer arb\n"
            "Thu: MLB arb\n"
            "Fri: NBA arb + NHL recreational\n\n"
            "Pattern: Looks diverse, not robotic\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>3️⃣ TIMING STRATEGY</b>\n\n"
            "❌ Red flags:\n"
            "• Bet within seconds of line posting\n"
            "• Only bet closing lines\n"
            "• 3:47 AM on Turkish league\n"
            "• Perfect execution every time\n\n"
            "✅ Smart timing:\n"
            "• Wait 2-5 min after line posts\n"
            "• Bet during peak hours (12-1 PM, 7-9 PM)\n"
            "• Occasional delayed bets\n"
            "• Some weekends, some weekdays\n\n"
            "Reality: Good arbs last 10-30 minutes\n"
            "You don't need to be FIRST, just fast enough\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "<b>4️⃣ WITHDRAWAL PATTERNS</b>\n\n"
            "❌ Obvious pattern:\n"
            "• Deposit Monday\n"
            "• Arb all week\n"
            "• Withdraw Friday\n"
            "• Repeat forever\n\n"
            "✅ Natural pattern:\n"
            "• Deposit reasonable amounts\n"
            "• Let balance fluctuate\n"
            "• Withdraw monthly or bi-monthly\n"
            "• Keep 20-30% balance on book\n\n"
            "Example:\n"
            "Week 1: Deposit $1,500\n"
            "Week 2-4: Bet, balance grows to $2,300\n"
            "Week 5: Withdraw $800\n"
            "Continue with $1,500 balance\n\n"
            "Looks like: Recreational winner\n"
            "Not: Professional arbitrageur\n\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        )
    
    kb = [
        [InlineKeyboardButton(
            text="➡️ Section 2 (Part 2)" if lang == 'en' else "➡️ Section 2 (Part 2)",
            callback_data="guide_pro_tips_2b"
        )],
        [InlineKeyboardButton(
            text="◀️ Section 1" if lang == 'en' else "◀️ Section 1",
            callback_data="guide_pro_tips_1"
        )],
        [InlineKeyboardButton(
            text="◀️ Back to Guide" if lang == 'en' else "◀️ Retour au Guide",
            callback_data="learn_guide_pro"
        )]
    ]
    
    await callback.message.edit_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=InlineKeyboardMarkup(inline_keyboard=kb)
    )
